### ISSUE TITLE
Overzicht alle activiteiten - Laravel

### ISSUE THREAD

**Issue by BenBerkenbosch** [GijsPampiermole/Actievadis#16]

**Comment by GijsPampiermole** [comment]
Has moved to different tasks
[HTML Issue](https://github.com/GijsPampiermole/Actievadis/issues/33) || [Html Branch](https://github.com/GijsPampiermole/Actievadis/tree/33-html-activity-overview)
[PHP Issue](https://github.com/GijsPampiermole/Actievadis/issues/34) **already merged**
